---
- name: Manage Docker Containers
  hosts: all
  become: true
  tasks:
    - name: Stop running containers
      command: docker stop $(docker ps -q)
      ignore_errors: true
      become_user: your_docker_user

    - name: Remove stopped containers
      command: docker rm $(docker ps -aq)
      ignore_errors: true
      become_user: your_docker_user

    - name: Pull Docker image from Docker Hub
      command: docker pull mallikarjun2020/webapp:latest
      become_user: your_docker_user

    - name: Create Docker container
      command: docker run -d --name simple-devops-container -p 8080:8080 mallikarjun2020/webapp:latest
      become_user: your_docker_user
